EclipseFdn/iot.eclipse.org

layouts/index.html
=> Move GTM noscript to the body of the page

layouts/404.html
=> remove double header on 404 page

layouts/case-studies/single.html
=> Fix html version of case-studies

content/case-studies/bosch-leadership in-eclipse-iot.md
=> Update Bosch Pursues An Open Strategy To Transform IoT

layouts/section/case-studies.html
=> Sort case studies by pubdate

content/news/2018-09-28-eclipse-iot-day-singapore.md, content/news/2018-10-02-case-study-how-bosch-is-succeeding-with-open-source-at-eclipse-iot.md
=> #22 - Add latest news

content/news/2018-10-05-welcome-jameka.md
=> #24 - Add a new News item

layouts/section/case-studies.html
=> #25 - Update text in Case Studies page

layouts/section/open-iot-challenge.html
=> IoT Challenge - Page Edits - https://iot.eclipse.org/open-iot-challenge/

content/news/2018-10-22-industrial-iot-world-atlanta.md
=> #30 - Add news item

content/news/2018-10-18-a-primer-on-digital-twins-in-the-iot.md, content/news/2018-10-22-pnnl-s-volttron-goes-way-beyond-building-energy-management.md, content/news/2018-10-31-edgeworx-iofog-platform-drills-software-down-to-the-edge.md
=> #33 #34 #35 - Add news items

content/events/2018-12-13-kubecon-cloudnativecon-na.md
=> #42 - Add a new event for Kubecon + CloudnativeCon NA

content/news/2018-11-20-open-iot-challenge.md
=> #41 - Add a news item

content/events/2018-12-10-kubecon.md, content/events/2018-12-13-kubecon-cloudnativecon-na.md
=> Fix Kubecon event

content/events/2018-12-11-kubecon.md
=> Update Kubecon dates

layouts/section/working-group.html
=> #50 - Remove bullet from benefits on membership page

content/news/2019-02-07-iot-day-grenoble-2019.md
=> #49 - Add new announcement for IoT Day Grenoble 2019

layouts/section/membership.html
=> #64 - Update the Membership benefits

layouts/index.html
=> #63 - Update newsletter link

content/working-group/_index.md
=> Fix alias from /working-group

content/news/2019-02-20-top-25-iot-startups-to-watch-in-2019.md, content/news/2019-02-21-war-stories-about-edge-computing-on-kubernetes.md, content/news/2019-02-26-eclipse-iot-has-over-350-contributors-working-on-37-projects.md, content/news/2019-02-26-eclipse-iot-reaches-new-milestones-in-open-source-iot-leadership.md
=> #70 #71 #73 - Add news items

layouts/membership/section.html
=> Updates to membership page #74

layouts/membership/section.html
=> Update Join Eclipse IoT blurb text

layouts/eclipse-iot-day-santa-clara-2019/section.html
=> #78 - Update organizers info, fix typo in speakers list

content/news/2019-03-07-time-is-running-out.md
=> #81 - Add new news item

layouts/open-iot-challenge/section.html
We cancelled the Open IoT challenge 5.0 and need to update the page to reflect that fact.
=> Changing challenge page to announce cancellation.

content/news/2019-02-20-integrating-eclipse-iot.md, content/news/2019-02-28-eclipse-iot-newsletter-february-2019.md
=> #84 - Add news items

layouts/membership/section.html
After a conversation with Paul W and Perri, we decided to suspend our contact form experiment for the time being, as we did for Jakarta EE.
=> Temporarily remove the "Fill out Contact Form" button and blurb.

layouts/eclipse-iot-day-santa-clara-2019/section.html
=> #89 - Update IoT Day 2019 schedule information

content/resources/2015-12-22-case-study-01.md, content/resources/2015-12-22-case-study-02.md, content/resources/2016-01-27-case-study-03.md, content/resources/2016-10-14-white-paper-IoT-architectures.md
These pages already exist under case study or white paper section
=> remove duplicates

layouts/membership/section.html
=> Update our line of code count to 3.9 million.

layouts/membership/section.html
=> Hide the "Join Eclipse IoT button" in the header of the "Join Us" page.

content/news/2019-04-08-new-survey-of-more-than-1-700-iot-developers-reveals-top-hardware-software-stack-choices.md
=> #108 - Add a new community news

layouts/devices/section.html
=> Replace Edje mention with MRAA.

layouts/case-studies/section.html
=> #117 - Fix the case studies page

content/events/2019-06-04-eclipse-iot-day-paris.md
=> #114 - Add IoT Day Paris in the events section

content/news/2019-04-17-want-to-the-know-future-of-iot-ask-the-developers.md
=> #113 - Add new community news item

content/news/2019-05-16-eclipse-iot-day-paris-saclay-2019.md
=> #123 - Add new community news

content/events/2019-10-21-ece2019.md, content/news/2019-05-27-industry-leaders-red-hat-eurotech-and-cloudera-join-forces-eclipse-foundation.md
=> #126 #127 - Add new event and news item

content/news/2019-06-11-eclipsecon-europe-call-for-papers-open.md
Added news article for ECE 2019.
Change-Id: I4c205246e0dbb5a699afd7589eceff2a05752231
=> ECE 2019: Call for Papers Now Open! Please add under 'Community...#135

content/resources/2019-02-21-lighting-solution-using-kapua-and-kura-platforms.md, content/resources/2019-03-13-revolutionizing-iiot-with-sparkplug-tahu.md, content/resources/2019-03-27-exploring-trend-toward-edge.md, content/resources/2019-04-17-yaks-distributed -heterogeneous-key-value-store-iot.md, content/resources/2019-05-21-developing-iot-applications-using-intel-system-studio.md, content/resources/2019-05-21-eclipse-volttron-overview-of-the-platform.md, content/resources/2019-05-21-exploring-trend-toward-edge.md, content/resources/2019-05-21-machine-learning-with-eclipse-deeplearning4j.md, content/resources/2019-05-21-mraa-upa-eclipse-iot-projects--eclipse-iot-day-santa-clara.md, content/resources/2019-05-21-state-of-the-union--eclipse-iot-day-santa-clara.md, content/resources/2019-05-21-using-eclipse-mqtt-sparkplug-iiot-digital-transformation-toolkit.md, content/resources/2019-05-21-which-os-rtos-makes-sense-for-your-constrained-device.md
Added all 12 videos requested. Covers feature requests 139-150.
Change-Id: Id6224feb7567ecdce00849db4f67acae863491fe
=> Please add this video to articles/video page on ... #139

content/news/2019-06-14-become-a-sponsor-at-eclipsecon-europe.md
Change-Id: Ia37b25f4e7e1e909eda86ea549c8725a483b43ca
=> Become a Sponsor at EclipseCon Europe 2019 #152

content/news/2019-06-25-eclipse-iofog-evolving-toward-native-kubernetes-orchestration-edge-.md
Change-Id: I75832381a4a226e54346f312f6e848bb22afeff1
=> Please add to announcements #156

content/news/2019-06-27-iot-newsletter-is-here.md
Change-Id: I52dfea3af59500f3a7410b311bd1df3f43f9faea
=> Please post IoT Newsletter: ... #158

content/news/2019-06-28-eclipsecon-europe-registration-open.md
Change-Id: I2cc920c9ec79b596958ac273bd64754dddd5c1fd
=> Registration is now open for EclipseCon Europe 2019! ... #159

layouts/membership/section.html
Added button to membership layout
Change-Id: I97c0bfe467553a260a711883099c0aef8d361029
=> Adding IoT contact us Button and Icon on the page #166

Dockerfile, Jenkinsfile, k8s/production.yml, k8s/staging.yml
=> Host IoT on EF k8s cluser #173

content/news/2019-09-10-from-building-blocks-to-iot-solutions.md
Added new community news item:  From building blocks to IoT solutions
Change-Id: Ie90dece689de8f80f507d3b98350b85fb8b06277
=> Please add to community news: ... #182

content/events/2019-10-17-eclipse-keyple-meet-up.md
Added new event for IoT in October.
Change-Id: Ia2d316b5d6e91f25f1650947116951c41c0099fe
=> Eclipse Keyple Meet up #184

content/events/2019-11-11-4days-of-4diac.md
Added new event to event content
Change-Id: I742cb01a10858b95093a8755a9f453ff7107e30c
=> 4days of 4diac #187

package.json, static/js/adopters.js
=> Add adopters json to javascript file

bin/adopters.sh, static/assets/js/eclipsefdn.adopters.js, static/js/adopters.js
=> Add logo version option for eclipsefdn.adopters plugin

README.md
=> Update README file with adopters plugin

data/adopters.yml
=> move othermo to Eclipse Ditto

layouts/shortcodes/adopters.html
=> Adopter page: projects should be sorted alphabetically #207

content/news/2019-10-10-participate-2019-iot-commercial-adoption-survey.md
=> Infra 3443 - Add IoT survey news item

content/member/kichwa-coders-canada.md
Change-Id: Ice16f4bcd352f71de5cfbea9b5e7423afb71bd17
=> Add Kichwa Coders Canada to the IoT website #213

.github/ISSUE_TEMPLATE/adopter_request.md
Change-Id: I6bb211bf99584f300a1a86fe97109f12fa0e8726
=> Updated adopter request template to require both logo formats

content/events/2019-12-09-edge-computing-world.md, content/news/2019-10-21-edge-computing-world.md
Added event and news item for Edge computing world. Includes changes for
#237
Change-Id: Iaa7eab2b3132be00d826f5909a5297b5ad76fbfa
=> Edge Computing World #236

content/news/2019-11-07-bosch-connectedworld-call-for-papers.md
=> Add to community news #245

data/adopters.yml
=> add ADLINK to Eclipse iceoryx #243

content/news/2018-12-10-2018-launch-edge-native.md
=> Edge Native WG PR #259

.travis.yml, layouts/membership/members.html, netlify.toml
Added sort to all member ranges based on member Title.
=> Member listing should be sorting alphabetically *and* case-... #255

.travis.yml, Dockerfile, Jenkinsfile, netlify.toml
=> Fix hugo version

content/member/v2com.md
=> #285 - Remove V2com from the Members page

content/events/2020-02-14-iotdaygrenoble.md, content/events/2020-02-17-boschconnectedexperience.md, content/events/2020-02-19-boschconnectedworld.md, content/events/2020-03-19-fossasiasummit.md
=> Adding Q1 2020 events.

layouts/eclipse-iot-and-edge-day-san-jose-2020/section.html, static/eclipse-iot-and-edge-day-san-jose-2020/css/style.css
=> fix logo and typos

layouts/index.html
=> Broken link to whitepaper on the home page #300

data/adopters.yml
=> #324 - Update order of adopters for Autoware Foundation

content/events/2019-10-17-eclipse-keyple-meet-up.md, content/events/2019-10-21-ece2019.md, content/events/2019-11-11-4days-of-4diac.md, content/events/2019-12-09-edge-computing-world.md, content/events/2020-02-14-iotdaygrenoble.md, content/events/2020-02-17-boschconnectedexperience.md, content/events/2020-02-19-boschconnectedworld.md, content/events/2020-03-19-fossasiasummit.md, content/events/2020-04-09-iotandedgeday2020.md
=> Update dates in events

layouts/community/summary.html, layouts/news/section.html, layouts/shortcodes/home-news.html, less/_components/resources.less
=> Removed extra 'with' calls, fixed accessibility on resources page

archetypes/events.md, archetypes/news.md
=> fix archetypes

Dockerfile
=> minify output

layouts/shortcodes/page-adopters.html, less/_components/adopters.less
=> #353 - Update to adopters page

content/news/2018-12-10-2018-launch-edge-native.md, content/news/2020-02-03-sparkplug-launch.md, content/news/2020-03-10-iot-commercial-adoption-survey-2019.md, layouts/shortcodes/home-eclipse-foundation.html
Fixes issue https://github.com/EclipseFdn/iot.eclipse.org/issues/358.
=> Home page and news tweaks

less/_components/quicksilver/featured-members.less, static/assets/css/styles.min.css
=> Update members title margin

layouts/shortcodes/page-adopters.html
=> #333 - Add anchors to adopters page

.github/ISSUE_TEMPLATE/adopter_request.md
=> #352 - Update the adopters request form

data/adopters.yml
=> Kynetics should be under hawkbit

layouts/shortcodes/home-stats.html
=> #381 - Update stats on home page

less/_components/quicksilver/featured-events.less, less/_components/quicksilver/featured-news.less, static/assets/css/styles.min.css
=> #383 - Update styles for news and events titles

content/news/2020-03-13-iot-adoption-continues-to-grow-at-a-slow-and-steady-pace.md, content/news/2020-03-13-the-eclipse-foundation-releases-iot-commercial-adoption-survey-detailing-spend-target-markets-and-relevant-applications.md, content/news/2020-03-19-iot-adoption-survey.md, content/news/2020-04-14-iot-adoption-before-and-after-covid19.md
=> #388 #389 #390 #391 - Add new News items

content/news/2020-03-10-iot-adoption-survey-offers-insight-industry-landscape.md, content/news/2020-03-10-the-eclipse-foundation-releases-iot-commercial-adoption-survey-results.md, content/news/2020-03-11-40-per-cent-of-organisations-plan-to-increase-their-iot-spending-in-the-next-fiscal-year-survey.md, content/news/2020-03-11-deploy-iot-solutions-22-more-plan-to-study.md, content/news/2020-03-11-rate-of-iot-adoption-is-slower-than-expected-says-eclipse-foundation.md, content/news/2020-03-12-eclipse-foundation-survey-iot.md, content/news/2020-03-12-survey-says-slow-and-steady-iot-adoption-continues.md, content/news/2020-03-13-iot-news-of-the-week-for-march-13-2020.md, content/news/2020-03-13-survey-less-than-40-of-companies-are-deploying-iot.md, content/news/2020-03-19-the-internet-of-things-vs-iot-hype.md, content/news/2020-03-20-under-40-companies-deploying-iot-solutions.md, content/news/2020-03-27-eclipse-iot-survey.md
=> #397 #398 #399 - Add more News items

data/adopters.yml
=> #406 #407 - Add Pragmatic minds and Pragmatic industries to adopters

data/en/eclipse-virtual-iot-2020/registration.yaml
Please make sure to merge this as soon as possible; I cannot start promoting this without the actual event date on the page. Thanks! :-)
=> Adding date and time of the event to the page.

config.toml
=> Move the "Resources" section from the "Community" landing page to...#372

content/eclipse-virtual-iot-2020/_index.md, content/events/2020-05-28-virtualiotandedgeday2020.md
Please process the following related PRs at the same time:
https://github.com/EclipseFdn/edgenative.eclipse.org/pull/45
https://github.com/EclipseFdn/sparkplug.eclipse.org/pull/25
=> Virtual IoT and Edge Native Day 2020 tweaks

content/_index.md, data/featuredstory.yml, less/styles.less, less/transient.less, static/assets/css/styles.min.css
Change-Id: I32e313141594d806e2b4001e3241c9b32e22f372
=> Add Banner to IoT.eclipse.org #422

data/featuredstory.yml
=> #422 - Update title of developer survey in featured story

content/news/2020-05-11- iot-developer-survey-goes-to-the-edge.md
=> Add Mike's blog to news #430

content/events/2020-09-18-sam-iot.md
=> Add SAM IoT to event list #433

content/news/2020-06-09-10-best-iot-development-tools.md
=> Add news: 10 Best IoT Development Tools of 2020 #452

content/community/resources/videos/2020-04-09-zwilling-mit-ditto-plc4x.md, content/community/resources/videos/2020-05-20-ultimate-solution-for-iot-connectivity-hono.md, content/community/resources/videos/2020-05-27-semantic-modelling-in-action.md, content/community/resources/videos/2020-06-18-update-ota-made-easy.md
=> Add new videos in the Resources section on iot.eclipse.org #462

layouts/shortcodes/home-members.html
=> Fix the "members" section to indicate that there are more than ...#485

Dockerfile, Jenkinsfile
=> Switch to stable-alpine-for-hugo

data/adopters.yml
=> Please List Eurotech with the Paho Project as Adopter #521

data/adopters.yml, static/assets/images/adopters/logo-ericsson-white.svg, static/assets/images/adopters/logo-ericsson.svg
See https://github.com/eclipse/leshan/issues/830#issuecomment-638651182.
=> Add Ericsson as Leshan adopter.

content/community/resources/videos/2020-04-09-zwilling-mit-ditto-plc4x.md, content/community/resources/videos/2020-05-20-ultimate-solution-for-iot-connectivity-hono.md, content/community/resources/videos/2020-05-27-semantic-modelling-in-action.md, content/community/resources/videos/2020-06-18-update-ota-made-easy.md, content/community/resources/videos/2020-11-05-scale-ing-inventory-management.md
=> Add video #550 and fix some video dates

data/adopters.yml
=> Add Bosch to Zenoh #569

content/community/resources/videos/2020-11-17-code-free-smart-agriculture-p1.md, content/community/resources/videos/2020-11-17-code-free-smart-agriculture-p2.md
=> Add Greg video #571

content/community/resources/videos/2020-12-15-robotic-courier-network.md
=> add Greg new video

.travis.yml, Dockerfile, Jenkinsfile, netlify.toml, package-lock.json, package.json
This is for https://github.com/EclipseFdn/hugo-solstice-theme/issues/191
=> update Hugo theme to make adopters page hashtag work

babel.config.json, package-lock.json, package.json, webpack.mix.js
=> Update theme to 0.0.111

data/testimonials.yml
Fix #589 
I think we should wait for discuss with Paul? 🤔 
=> Update Bosch Name #589

data/testimonials.yml
=> Update Stefan Job title

content/community/_index.md
=> Broken links in the Community page #599

content/eclipse-virtual-iot-2021/_index.md, data/en/eclipse-virtual-iot-2021/agenda.yml
For [issue625](https://github.com/EclipseFdn/iot.eclipse.org/issues/625)
=> Updated agenda with recordings

layouts/shortcodes/projects/page-sandboxes.html
Signed-off-by: Achim Kraus <achim.kraus@bosch.io>
=> Update Leshan's sandbox url to eclipseprojects.io.

content/community/resources/videos/2021-06-02-open-source-software-for-industrial-iot.md
For [issue81](https://github.com/EclipseFdn/sparkplug.eclipse.org/issues/81)
=> Added a new IoT video

js/projects.js, layouts/shortcodes/page-projects.html
Updates aall of the projects according to info available on GH issue. Updates buttons, adds new edge category,  tidies up old projects
=> Content updates on the IoT WG projects webpage #635

layouts/partials/footer_custom.html, layouts/shortcodes/home-newsletter.html
Fixes [issue640](https://github.com/EclipseFdn/iot.eclipse.org/issues/640)
=> Replaced MailChimp IoT newsletter form with HubSpot form

layouts/shortcodes/page-anniversary.html, less/styles.less
Fixes [issue657](https://github.com/EclipseFdn/iot.eclipse.org/issues/657)
=> Added Press Release and updated the styles

package-lock.json, package.json, webpack.mix.js
For [issue413](https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/413)
=> Updated webpack

content/_index.md, content/anniversary/_index.md, less/styles.less
Fixes [issue664](https://github.com/EclipseFdn/iot.eclipse.org/issues/664)
=> Added anniversary logo to jumbotron

content/_index.md, content/membership/join-us/_index.md, layouts/shortcodes/membership/join-us.html
For [issue666](https://github.com/EclipseFdn/iot.eclipse.org/issues/666)
=> Embedded membership form

config.toml
For https://gitlab.eclipse.org/eclipsefdn/it/websites/eclipse.org/-/issues/94
=> Fixed the brand guidline link

config.toml, layouts/membership/section.html, layouts/shortcodes/membership/content.html, less/styles.less
Fixes https://github.com/EclipseFdn/iot.eclipse.org/issues/681
=> Updated the mobile view style
